### ISSUE TITLE
Create view for Friends view 

### ISSUE THREAD

**Issue by PpesR** [PpesR/Shared-Trip#39]

**Comment by markhenrip** [comment]
Need 2 layouts: 

1. one that has a RecyclerView. Basically a master layout to house all the friends' events (2.). Just change fragment_friends.xml.
2. one that represents a single friend event. Must have:
-- TextViews for event name, location and friend's name
-- larger ImageView for event's picture
-- smaller (circle shaped) ImageView for friend's profile picture
